# Copyright 2023-2025 Amazon.com, Inc. or its affiliates.

name: osml_models
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.10.12
  - conda-forge::gdal=3.7.2
  - conda-forge::proj=9.3.0
  - conda-forge::numpy=1.26.4
